# Generated by Django 4.2.20 on 2025-03-27 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signallog',
            name='is_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='thread_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
